### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samwin20**
add a tool to boost productivity and image converter

### CODE REVIEW

**Comment by samwin20** [comment]
Hello! thank you in advance

**Review by selfishprimate — CHANGES_REQUESTED** [review]
Hey there! Please enter the same information productivity.yaml file under the data folder. These yaml files feed the website's content. To learn more about contribution please read the CONTRIBUTING.md file. And please use a punctuation at the end of the description text.

**Comment by samwin20** [comment]
> Hey there! Please enter the same information productivity.yaml file under the data folder. These yaml files feed the website's content. To learn more about contribution please read the CONTRIBUTING.md file. And please use a punctuation at the end of the description text.

Done :) thanks

**Review by selfishprimate — CHANGES_REQUESTED** [review]
Hey there, again! Can you please move this resource under the "Others" section? Because it does nothing to do with the "Productuvity."

Thank you.

**Comment by samwin20** [comment]
> Hey there, again! Can you please move this resource under the "Others" section? Because it does nothing to do with the "Productuvity."
> 
> Thank you.

Done!

**Pull request merged**
