### PR TITLE
Added Taskade

### PR DESCRIPTION
**Pull request by johnxie**
Please consider including [Taskade](https://taskade.com), thanks!

### CODE REVIEW

**Review by selfishprimate — CHANGES_REQUESTED** [review]
The items must be added in alphabetical order. According to this, [Taskade] must be listed before [Zapier].

Another thing is, you have to add the same information (name, description, and the link) into the [productivity.yaml] file as well in order to provide content for the web site too. So these *.yaml files are located under [data] folder and they're for the web site content.

Please inspect the code in the [productivity.yaml] file, try use the same format and add the same information for Taskade (name, description, and the link) here.

Thank you for your patient.

**Comment by johnxie** [comment]
Thanks, accidentally made a 2nd PR for the productivity yaml file fix, hope that is ok.

**Review by selfishprimate — APPROVED** [review]
Seems great!

**Comment by selfishprimate** [comment]
Add [Taskade] --> [Productivity]

**Pull request merged**
